# Generated by Django 5.2.12 on 2026-03-31 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("continent", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountryLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("is_official", models.BooleanField()),
                ("percentage", models.FloatField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.country"
                    ),
                ),
            ],
        ),
    ]
