# Generated by Django 5.2.12 on 2026-05-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_country_capital"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["continent", "name"],
                name="country_cont_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="countrylanguage",
            index=models.Index(
                fields=["language", "country"],
                name="lang_country_idx",
            ),
        ),
    ]
